# Generated by Django 5.0.2 on 2024-03-02 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории которое будет отображаться на сайте')),
                ('name_category', models.CharField(max_length=255, unique=True, verbose_name='Название категории подробное')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('isPublished', models.BooleanField(default=True, verbose_name='Отображение категории на сайте')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Раздел')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('isPublished', models.BooleanField(default=True, verbose_name='Отображение раздела на сайте')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Размер одежды')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Размер одежды',
                'verbose_name_plural': 'Размеры одежды',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('unit', models.IntegerField(verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за штуку')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Основное фото продукта')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('isPublished', models.BooleanField(default=True, verbose_name='Отображение продукта на сайте')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.categories', verbose_name='Категория одежды')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.sections', verbose_name='Раздел сайта')),
                ('size', models.ManyToManyField(to='Shop.sizes', verbose_name='Размер одежды')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Вещи',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Дополнительное фото продукта',
                'verbose_name_plural': 'Дополнительные фото продуктов',
            },
        ),
    ]
