# Generated by Django 5.0.2 on 2024-03-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='media/photos/%Y/%m/%d/', verbose_name='Основное фото продукта'),
        ),
    ]
