# Generated by Django 5.0.2 on 2024-05-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='sections',
            name='category',
            field=models.ManyToManyField(to='Shop.categories', verbose_name='Категория'),
        ),
    ]
