# Generated by Django 5.0.2 on 2024-05-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_remove_product_category_sections_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='name_category',
        ),
    ]
