# Generated by Django 5.0.2 on 2024-06-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_color_product_colors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='Colors',
        ),
    ]
