# Generated by Django 5.0.2 on 2024-06-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_rename_color_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shop.categories', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
