# Generated by Django 5.0.2 on 2024-08-12 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_remove_sections_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sizes',
            name='slug',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество товара')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.colors', verbose_name='Цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product', verbose_name='Конкретный товар')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.sizes', verbose_name='Рвзмер')),
            ],
        ),
    ]
