# Generated by Django 5.0.2 on 2024-09-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_remove_categories_slug_remove_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Конкретный товар', 'verbose_name_plural': 'Конкретные товары'},
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.sizes', verbose_name='Размер'),
        ),
    ]
