# Generated by Django 5.0.2 on 2024-08-12 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shop', '0009_remove_categories_slug_remove_product_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя заказчика')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефонный номер заказчика')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('comments', models.TextField(verbose_name='Коментарий к заказу')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basket.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_quantity', models.PositiveSmallIntegerField(verbose_name='Количество товара которое заказ заказчик')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.item', verbose_name='Конкретный товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basket.order', verbose_name='Номер заказа')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
