# Generated by Django 5.0.2 on 2024-08-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая сумма заказа'),
            preserve_default=False,
        ),
    ]
