# Generated by Django 5.0.2 on 2024-08-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0002_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='comments',
            new_name='comment',
        ),
    ]
