# Generated by Django 5.0.2 on 2024-09-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0003_rename_comments_customer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=18, verbose_name='Телефонный номер заказчика'),
        ),
        migrations.AlterField(
            model_name='products',
            name='selected_quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Количество товара которое заказал заказчик'),
        ),
    ]
